version: 2
main-branch: main
release-branch:
  prefix: release/
  suffix: .x
changelog:
  # Determine which PR changelog options are available and which end up in the changelog
  options:
    type:
      feature: add
      breaking: add
      compatible: add
      optimisation: add
      bugfix: add
      refactoring: skip
      test: skip
      maintenance: skip
      release: skip
      documentation: skip

      # deprecated, left here only for backwards compatible changelog generation
      improvement: add
