name: "Haddock documentation"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            substituters = https://cache.iog.io/ https://cache.nixos.org/

      - uses: rrbutani/use-nix-shell-action@v1

      - name: Update cabal indices
        run: |
          cabal update

      - name: Build whole project
        run: |
          cabal build all

      - name: Build documentation
        run: |
          cabal haddock-project --output=./haddocks --internal --foreign-libraries

      - name: Compress haddocks
        run: |
          tar -czf haddocks.tgz -C haddocks .

      - name: Upload haddocks artifact
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        continue-on-error: true
        with:
          name: haddocks
          path: ./haddocks.tgz

      - name: Deploy documentation to gh-pages 🚀
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN || github.token }}
          publish_dir: haddocks
          cname: cardano-cli.cardano.intersectmbo.org
          force_orphan: true
