name: "Haskell Language Server works"
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
 
permissions:
  contents: read
  
jobs:
  test-hls-works:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - uses: cachix/install-nix-action@daddc62a2e67d1decb56e028c9fa68344b9b7c2a
      with:
        nix_path: nixpkgs=channel:nixos-23.11
    - run: nix develop --accept-flake-config --command bash -c "cabal update; haskell-language-server"
